### PR TITLE
Core: RemoteV3 new branch of AmeisenNavigation `multi-version-guess-z-coord`

### PR DESCRIPTION
**Pull request by Xian55**
Changes: 
* Core: Added `PathVisualizer`. Currently `PPather` only works with Wotlk maps for viz. Not suitable for Cata maps.
* Core: While using `RemoteV3` and `RemoteV1` is available as well, the generated paths and player positions can be visualized.
* Core: RemoteV3 uses new build of `AmeisenNavigation` which is more performant during startup and supports multiple mmaps versions.

---

Its worth to point out that [AmeisenNavigation](https://github.com/Xian55/AmeisenNavigation/tree/feature/multi-version-guess-z-coord) uses a new branch called `multi-version-guess-z-coord`. This version of AmeisenNavigation can be built using Visual Studio 2022 but still requires the `C++` component!

**Install dependencies for `AmeisenNavigation.Server`**:
1. First you have to download **Visual Studio 2022**
1. Make sure to check the `Desktop development with C++` box
1. image

**Steps to make make RemoteV3 / `AmeisenNavigation.Server` working**:
1. Extract the `mmaps` and copy anywhere you want, like `C:\mmaps`
1. Get the [multi-version-guess-z-coord branch](https://github.com/Xian55/AmeisenNavigation/tree/feature/multi-version-guess-z-coord)
1. Open the solution file.
1. Be sure to set Target platform from `Any CPU` to either `x86` or `x64`
1. Unload **AmeisenNavigation.Exporter** project(right click -> unload project)
1. image
1. Select **AmeisenNavigation.Server** Press rebuild.
1. Navigate to the `AmeisenNavigation.Server` build location and find `config.cfg`
1. Edit the last line of the file to look like `sMmapsPath=C:\mmaps`

If you have problem getting the AnTCP.Client nuget package, you have to install it manually from [here](https://github.com/Jnnshschl/AnTCP/releases).

### CODE REVIEW

**Comment by starnodes** [comment]
I followed the instructions but am getting a build error. Can you tell me what could be the problem?
[build log.txt](https://github.com/Xian55/WowClassicGrindBot/files/15491633/build.log.txt)

Or maybe you can publish the compiled version?
Thanks!

**Comment by Xian55** [comment]
I'm getting the same error, i'm not sure what's changed. 
I had no issues compiling in prior, maybe a windows update or something.

I'm only having an old Debug build, but it should be work.
[AmeisenNavigationServer_x64_Debug.zip](https://github.com/Xian55/WowClassicGrindBot/files/15491709/AmeisenNavigationServer_x64_Debug.zip)

**Comment by Xian55** [comment]
I've recompiled the the project, with the latest compiler it builds now. [Pushed the fix](https://github.com/Xian55/AmeisenNavigation/commit/0ccd5c19104206788b5dab02779d1ea7d71d5a39).

In case it does not work at your side still, here's a x64 release build of the server with the latest compiler.
[AmeisenNavigationServer_x64_Release.zip](https://github.com/Xian55/WowClassicGrindBot/files/15491804/AmeisenNavigationServer_x64_Release.zip)

Thanks for letting me know about the problem, i hope the issue getting resolved at your end, have a nice day!

**Comment by LienSimen** [comment]
Steps that worked for me:
1. Target platform x86
2. Downloading [AnTCP.Client.1.1.1.nupkg](https://github.com/Jnnshschl/AnTCP/releases/download/1.1.1/AnTCP.Client.1.1.1.nupkg) and in visual studio Tools-> nuGet Package Manager -> Package Sources -> C:\YourNuGetDownloadFolder and press update.
3. Rebuild .Pack for AmeisenNavigation.Pack.lib not found, then rebuild server.
4. Run DriverBooster to get Json, then change map and port (from 47110 to 47111)

**Pull request merged**
