### PR TITLE
auto loot issue

### PR DESCRIPTION
**Pull request by CommanderSam**
Hello Xian good work on keeping the bot alive, I haven't been able to get auto loot to work for a month atleast.

The orgianal fork of the bot i didnt have any trouble with loot. Any class I use it just goes to mob and jumps but skips looting all together.

I have auto loot ticked and target last target key binded.

### CODE REVIEW

**Comment by CommanderSam** [comment]
Hello Xian, I've been having loot issues where it skips entierly like the guy above. I've actually haven't had it succesfully loot once. I need some help if possible via discord

**Comment by CommanderSam** [comment]
@Xian55 Hello, I'm getting an error when using the new branch. 
Capture

**Comment by Xian55** [comment]
Why did you a PR from this branch?
The feature was not complete...

**Comment by CommanderSam** [comment]
I'm using the main branch but the bot never loots. I have the same issues as @futureshockk  @Xian55 

I didn't mean to do a PR i'm still new to Github

**Comment by Xian55** [comment]
Join discord for quick discuss.
https://discord.gg/c9QcGhm

**Pull request closed without merging**
