### PR TITLE
Addon [1.2.5]: Improved interactive `AttendedGather` mode

### PR DESCRIPTION
**Pull request by Xian55**
Key Changes for `AttendedGather` mode -> `WaitForGathering`:
* Instead of Stopping and Restarting required. When a gatherable yellow node found at the minimap the `WaitForGathering` Goal takes over the control. 
* Requires User interaction in order to proceed.
* Uses a non blocking state machine to handle different state of the gathering process.
* Considers failed gathering attempts and awaits for user input to proceed.
* Supports multiple taps from Mining vein.
* During `FollowRouteGoal` uses more strict distances to determine waypoint reached state.
* `Gather` tab got improved layout to supply the necessary prompt information.

Improvements:
* `MountHandler`: Considers more about the player be able to use mount.
* `MinimapNodeFinder`: Reports the amount of distinctly visible nodes.

### CODE REVIEW

**Comment by horstc** [comment]
Hey, thank you, great progress on this! Got one bug, for me bot doesn't mount at all. UseMount is set true in class profile.

**Comment by Xian55** [comment]
Hello there! 👋 

Please open an issue about it, fill the form. Upload files such as logs (full content), `ClassConfiguration` file and Path file in order to have a clear view what's going on. 🙇

**Comment by Xian55** [comment]
Take a look at #281

**Comment by horstc** [comment]
Hey, thank you mate! Sorry, last days had no time to do further testing and create an issue, but your solution worked fine. 🙂 Didn't know there was this keymap baked in. 👍

**Pull request merged**
