### PR TITLE
Make x64 bit build possible - using platform dependent `StormLib.dll`

### PR DESCRIPTION
**Pull request by coolzoom**
It is now working correctly at x64 mode!

See Ladislav Zazula's response here.
https://github.com/ladislav-zezula/StormLib/issues/260

However, this project may not work with x86 build anymore.
@Xian55  Any suggestions?

### CODE REVIEW

**Comment by Xian55** [comment]
Hello, great improvement on managed building a x64 version of `StormLib.dll` 👏 

Based on the StormLib.dll size, is that a debug version? It seems quite big compare to the old one.

Can you tell what what settings, and compiler you have used ? 
* Visual studio version.
* Windows SDK version
* what target, as i see there are multiple Release and Debug versions in the build stormlib [build process](https://github.com/ladislav-zezula/StormLib/blob/7a664bf6be4377aabe03f118fcdb6d1d3abc48f5/make-msvc.bat#L49). 

> However, this project may not work with x86 build anymore.

Ye no wonder, since you replace the old x86 dll with x64 one... :D 

In order to support both version have to include both dlls and depending on what environment running in have to load the dll dynamically or at the startup. [example](https://stackoverflow.com/questions/16569257/load-x64-or-a-x86-dll-depending-upon-the-platform)

**Comment by coolzoom** [comment]
> Based on the StormLib.dll size, is that a debug version? It seems quite big compare to the old one.

Yes, it is a debug version StormLib.dll I compiled from the fresh source. Let me see if i can generate released version and push.

> In order to support both version have to include both dlls and depending on what environment running in have to load the dll dynamically or at the startup.

there're two functions are differnet at differnt mode,
at x86
[MarshalAs(UnmanagedType.LPStr)] string szExtracted,
at x64
[MarshalAs(UnmanagedType.LPWStr)] string szExtracted,

in c++ there is macro we could define the platform, what shall we do in the c# to call different function at different mode?

**Comment by Xian55** [comment]
Maybe this [helps](https://www.codeproject.com/Tips/852544/NET-Interop-with-and-bit-DLLs)

Basically have to create a wrapper. and somewhere at the init phase have to create an instance of the currently used platform specific implementation.

This way can set the solution to `AnyCPU`, and the runtime will determine what to load by trial and error

To avoid exception you can use the [following](https://www.codeproject.com/Messages/4962028/Suggesstion-for-Improvement)

**Comment by coolzoom** [comment]
> Maybe this [helps](https://www.codeproject.com/Tips/852544/NET-Interop-with-and-bit-DLLs)
> 
> Basically have to create a wrapper. and somewhere at the init phase have to create an instance of the currently used platform specific implementation.
> 
> This way can set the solution to `AnyCPU`, and the runtime will determine what to load by trial and error
> 
> To avoid exception you can use the [following](https://www.codeproject.com/Messages/4962028/Suggesstion-for-Improvement)

Let me see, looks like a tough one for me. lol

**Comment by coolzoom** [comment]
> Can you tell what what settings, and compiler you have used ?
> 
> * Visual studio version.
> * Windows SDK version
> * what target, as i see there are multiple Release and Debug versions in the build stormlib [build process]

I open the solution using Visual Studio 2022, since i also have Visual Studio 2010 installed, im selecting the Visual Studio 2010 as the compiler which has the best compatability, so there is no Windows SDK required,
Also in the latest commit im selecting Win32 Release and x64 Release without those local options.
image

**Comment by coolzoom** [comment]
@Xian55  using a simpler method and tested it works, please review

**Comment by Xian55** [comment]
Yea the idea is the same, without creating an instance as suggested. Looking fine by me. 👏 

Did you make any test run if the MPQ extraction working and the pathfinder gives a path result, with 
* x64 
* x86

versions ?

**Comment by coolzoom** [comment]
> Yea the idea is the same, without creating an instance as suggested. Looking fine by me. 👏
> 
> Did you make any test run if the MPQ extraction working and the pathfinder gives a path result, with
> 
> * x64
> * x86
> 
> versions ?

Yup, tested both x86 and x64, the path finding and file extract working as intended, if you can please do some tests as well make sure i didnt break anything.

**Comment by Xian55** [comment]
Gonna do some test on my own with PathingAPI, reporting back soon! 🙇

**Comment by Xian55** [comment]
Tested every build variant. I've changed the default setup.

when the solution target is `AnyCPU` every project uses `AnyCPU` as target platform. The same goes for `x64`, `x64` is the target.

Not gonna bother with `x86` as `AnyCPU` can fall back if necessary. 

Also cleaned up the per project conditional builds, as the goal was to force the runnable project to `x86` which is no longer the case.

The pathfinder it self gives valid results in the following continents Azeroth, Kalimdor and Outland.

Northrend dataset is yet to be added, going to do it soon.

**Comment by Xian55** [comment]
Thanks for putting the time and effort to make this happen, this is huge. Last time i tried to achieve this i've failed miserably. 🙇

**Comment by Xian55** [comment]
While using `x64`, memory usage quite noticeable higher 🤔

**Comment by coolzoom** [comment]
> While using `x64`, memory usage quite noticeable higher 🤔

hmm, not sure why is that tbh…

**Comment by Xian55** [comment]
Something not right with the new stormlib.dll checking x86 build target to compare. Upon reaching `SFileOpenArchive` it takes **~50x** times slower to open the archive. Its quite noticable!

Checking out before the merge `dev` b658e77f5147e3c8180630abcc14cc48d8273ec3
x86 platform target `StormDll.SFileOpenArchive(file, Prio, Flags, hp);` executes in **56ms**

Current `dev` branch
x86 platform target `r = StormDllx86.SFileOpenArchive(file, Prio, Flags, out handle);` executes **2636ms**
x64 gives similar result 2500ms

It was an oversight from my part, i've only measured the path calculations excluding the MPQ archives loading time.


repro:
* Set PathingAPI startup project.
* [Uncomment the line](https://github.com/Xian55/WowClassicGrindBot/blob/dev/PathingAPI/Startup.cs#L26) to show up time measure
* start PathingAPI and click on [Tanaris FP to ZF (API Using Map Coords)](http://localhost:5001/api/PPather/MapRoute?uimap1=1446&x1=51.0&y1=29.3&uimap2=1446&x2=38.7&y2=20.1)

**Comment by Xian55** [comment]
May i ask where have you found these [Flags](https://github.com/Xian55/WowClassicGrindBot/blob/dev/PPather/Triangles/StormDll.cs#L96) it seems some of them doesn't match with [StormLib master](https://github.com/ladislav-zezula/StormLib/blob/7a664bf6be4377aabe03f118fcdb6d1d3abc48f5/src/StormLib.h#L308)

Like 
https://github.com/Xian55/WowClassicGrindBot/blob/dev/PPather/Triangles/StormDll.cs#L100
vs
https://github.com/ladislav-zezula/StormLib/blob/7a664bf6be4377aabe03f118fcdb6d1d3abc48f5/src/StormLib.h#L331

**Comment by coolzoom** [comment]
> May i ask where have you found these [Flags](https://github.com/Xian55/WowClassicGrindBot/blob/dev/PPather/Triangles/StormDll.cs#L96) it seems some of them doesn't match with [StormLib master](https://github.com/ladislav-zezula/StormLib/blob/7a664bf6be4377aabe03f118fcdb6d1d3abc48f5/src/StormLib.h#L308)
> 
> Like https://github.com/Xian55/WowClassicGrindBot/blob/dev/PPather/Triangles/StormDll.cs#L100 vs https://github.com/ladislav-zezula/StormLib/blob/7a664bf6be4377aabe03f118fcdb6d1d3abc48f5/src/StormLib.h#L331

Good find, those are I cherry-pick from some old file that just happened to work.
https://github.com/tomrus88/mywowtools/blob/master/StormLib/StormLibExample/StormLib.cs
while we use READ_ONLY mode and this flag has not really changed.
Do you think it might because of those flags?
or it could be something with the latest stormlib.dll modifications itself?

**Comment by Xian55** [comment]
That example from tomrus88 repo is outdated.

I've already dived into the `SFileOpenArchive` flags and `OpenFile` flag. Managed to reduce the initial loading time back to the original one. by using the following flags.

```cs
                Archive a = new(files[i], out bool open, 0,
                    OpenArchive.MPQ_OPEN_NO_LISTFILE |
                    OpenArchive.MPQ_OPEN_NO_ATTRIBUTES |
                    OpenArchive.MPQ_OPEN_NO_HEADER_SEARCH |
                    OpenArchive.MPQ_OPEN_READ_ONLY);
```

Working as before this PR merged. Just doing some more testing to make sure everything is properly.

---

However, the x64 memory usage is still a thing, on a specific scenario.
* x64 uses 1.1gb
* x86 uses 400mb

repro:

* Set PathingAPI startup project.

* start PathingAPI and scroll down to click on [Dun morogh Coldrige pass](http://localhost:5001/api/PPather/MapRoute?uimap1=1426&x1=33.76&y1=71.91&uimap2=1426&x2=39.0&y2=61.13)

**Comment by Xian55** [comment]
Should fix the loading time issue. https://github.com/Xian55/WowClassicGrindBot/commit/a3ea49b00418a988e7010d5f2765fe138cd8118b

**Pull request merged**
