### PR TITLE
Adding Icon to Toggle preview

### PR DESCRIPTION
**Pull request by coolzoom**
From:
image

To:
image

Just a little bit OCD. lol

### CODE REVIEW

**Comment by Xian55** [comment]
Can you resize the image to fit the text height ?

**Comment by Xian55** [comment]
Or just remove the Mouse part of it, feels redundant.

**Comment by coolzoom** [comment]
> Or just remove the Mouse part of it, feels redundant.

you mean remove the text label?

**Comment by Xian55** [comment]
Only keep this part of the image.
image with a scaled down to the font size

**Comment by Xian55** [comment]
Actually. https://useiconic.com/open already in the project. so i would rather choose and svg rather than a fixed bitmap file.

you can pick what you like, examples:
* [fullscreen-enter](https://useiconic.com/open#)
* [fullscreen-exit](https://useiconic.com/open#)
* [image](https://useiconic.com/open#)

look at the `NavMenu.razor` to how to include them

**Comment by coolzoom** [comment]
How about this one?
image

**Comment by Xian55** [comment]
This is good.

**Pull request merged**
