### PR TITLE
Adding missing end point for the remotepathfinder

### PR DESCRIPTION
**Pull request by coolzoom**

### CODE REVIEW

**Comment by Xian55** [comment]
Hi can you provide some context about this one?

Personally i wasn't encountered any defect in prior.

**Comment by coolzoom** [comment]
> Hi can you provide some context about this one?
> 
> Personally i wasn't encountered any defect in prior.

Hey man, 
are you also testing the RemoteV3 pathfinding? i managed to get the world coordinate and using the remotev3 which also returned the world coordinate, it indeed missing the endping point.

image


image


on how i made that happen please see my notes here https://github.com/Xian55/WowClassicGrindBot/issues/344#issuecomment-1200220060

**Comment by Xian55** [comment]
To be honest, since i did a tidy up on `PPather` project, felt enough to use only that.

I will take a look it soon, working on other things at the moment

**Comment by coolzoom** [comment]
all right, i will stick with the ppather for now.

**Comment by Xian55** [comment]
Hey, im busy with other stuff at the moment, sorry for the late reply.

i've been running RemoteV3 for couple of hours, seems working as intended.

The suggested fix may have a side effect, if i recall correctly, upon requesting a really long path which has more points then it reserved - this is the **512** on your posted screenshot, then you going to connect the last returned point and the destination, which may be a long distance away.

here's a really nice drawing. :')

image

I know an example for this, after you land the Azshara alliance flight point and the Goal Route is 
https://github.com/Xian55/WowClassicGrindBot/blob/dev/Json/path/_pack/40-50/Azshara/54-55%20High%20Beach.jpg

RemoteV3 ran out of the **512** limit and had to increase it from the config.

**Comment by coolzoom** [comment]
yes, also I found the recast navigation is not as promised as the ppather, it sometimes returns the straight path while there're gameobjects along the way, it may be because of my config or so. let me close this pr and will do some more tests.

**Comment by Xian55** [comment]
Yes, PPather is extracting the map tiles on the fly, including the WMO files and small objects, creates a navmesh then caches it. i've found it more precise for small routes, while taking its time for long path. Since i found ppather more precise in certain situations, spent some time to modernize the project. Later on could be transformed to use CASC file format instead of MPQ.

Based on the Constraints of RemoteV3, which based of a TrinityCore config file, have to compile the MapGenerator, and then compile the recast navmesh it self, this process requires far more time investment to find the right settings for player movement. You can opt in to bake single map tile, and tweak the TrinityCore settings then play with it in the recast navigation demo.

**Comment by coolzoom** [comment]
| Later on could be transformed to use CASC file format instead of MPQ.

using the CASC format would be a tough one, which requires the entire client data folder(huge), although there is CASC lib available, and the db2 structure has changed a lot. also need to understand what magic the ccode.dll is doing since there is not a source I could find.
or probably can just extract the required file from MPQ/CASE and zip it, then use zip method to extract them, or leave them as raw data.

so for retail client and client that are higher than 3.x it appears using the recast navigation is better. but yeah it seems not that correct compared with the existing ppather, still a lot needs to research.

meanwhile, pathfinding in instances, dungeons is really a thing, it seems there is no way besides memory hooking. moving forward it would be nice just focus on one pathfinding method and a fixed position system so this bot can be much more stronger and intellegence.

**Comment by coolzoom** [comment]
record here for backup, using IDEA to decompile the ccode.dll triBoxOverlap function see below.


```
BOOL __stdcall triBoxOverlap(float *a1, float *a2, float *a3, float *a4, float *a5)
{
  double v5; // st6
  double v6; // st7
  double v7; // st4
  double v8; // st5
  double v9; // st3
  double v10; // st2
  double v11; // st3
  double v12; // st4
  double v13; // st3
  double v14; // st2
  double v15; // st4
  double v16; // st3
  double v17; // st4
  double v18; // st3
  double v19; // st2
  double v20; // st4
  double v21; // st5
  double v22; // st4
  double v23; // st3
  double v24; // st4
  double v25; // st3
  double v26; // st4
  double v27; // st3
  double v28; // st5
  double v29; // st2
  double v30; // st2
  double v31; // st5
  double v32; // st2
  double v33; // st3
  double v34; // st2
  double v35; // st6
  float v37; // [esp+4h] [ebp-64h]
  float v38; // [esp+4h] [ebp-64h]
  float v39; // [esp+4h] [ebp-64h]
  float v40; // [esp+4h] [ebp-64h]
  float v41; // [esp+4h] [ebp-64h]
  float v42; // [esp+4h] [ebp-64h]
  float v43; // [esp+4h] [ebp-64h]
  float v44; // [esp+4h] [ebp-64h]
  float v45; // [esp+4h] [ebp-64h]
  float v46; // [esp+4h] [ebp-64h]
  float v47; // [esp+4h] [ebp-64h]
  float v48; // [esp+4h] [ebp-64h]
  float v49; // [esp+8h] [ebp-60h]
  float v50; // [esp+8h] [ebp-60h]
  float v51; // [esp+8h] [ebp-60h]
  float v52; // [esp+8h] [ebp-60h]
  float v53; // [esp+8h] [ebp-60h]
  float v54; // [esp+8h] [ebp-60h]
  float v55; // [esp+8h] [ebp-60h]
  float v56; // [esp+8h] [ebp-60h]
  float v57; // [esp+8h] [ebp-60h]
  float v58; // [esp+8h] [ebp-60h]
  float v59; // [esp+8h] [ebp-60h]
  float v60; // [esp+8h] [ebp-60h]
  float v61; // [esp+8h] [ebp-60h]
  float v62; // [esp+8h] [ebp-60h]
  float v63; // [esp+8h] [ebp-60h]
  float v64; // [esp+8h] [ebp-60h]
  float v65; // [esp+8h] [ebp-60h]
  float v66; // [esp+8h] [ebp-60h]
  float v67; // [esp+Ch] [ebp-5Ch]
  float v68; // [esp+Ch] [ebp-5Ch]
  float v69; // [esp+Ch] [ebp-5Ch]
  float v70; // [esp+Ch] [ebp-5Ch]
  float v71; // [esp+Ch] [ebp-5Ch]
  float v72; // [esp+Ch] [ebp-5Ch]
  float v73; // [esp+Ch] [ebp-5Ch]
  float v74; // [esp+Ch] [ebp-5Ch]
  float v75; // [esp+Ch] [ebp-5Ch]
  float v76; // [esp+Ch] [ebp-5Ch]
  float v77; // [esp+Ch] [ebp-5Ch]
  float v78; // [esp+Ch] [ebp-5Ch]
  float v79; // [esp+Ch] [ebp-5Ch]
  float v80; // [esp+Ch] [ebp-5Ch]
  float v81; // [esp+Ch] [ebp-5Ch]
  float v82; // [esp+Ch] [ebp-5Ch]
  float v83; // [esp+10h] [ebp-58h]
  float v84; // [esp+10h] [ebp-58h]
  float v85; // [esp+10h] [ebp-58h]
  float v86; // [esp+10h] [ebp-58h]
  float v87; // [esp+10h] [ebp-58h]
  float v88; // [esp+14h] [ebp-54h]
  float v89; // [esp+14h] [ebp-54h]
  float v90; // [esp+14h] [ebp-54h]
  float v91; // [esp+18h] [ebp-50h]
  float v92; // [esp+18h] [ebp-50h]
  float v93; // [esp+18h] [ebp-50h]
  float v94; // [esp+1Ch] [ebp-4Ch]
  float v95; // [esp+1Ch] [ebp-4Ch]
  float v96; // [esp+1Ch] [ebp-4Ch]
  float v97; // [esp+20h] [ebp-48h]
  float v98; // [esp+24h] [ebp-44h]
  float v99; // [esp+28h] [ebp-40h]
  float v100; // [esp+2Ch] [ebp-3Ch]
  float v101; // [esp+30h] [ebp-38h]
  float v102; // [esp+34h] [ebp-34h]
  float v103; // [esp+38h] [ebp-30h]
  float v104; // [esp+3Ch] [ebp-2Ch]
  float v105; // [esp+40h] [ebp-28h]
  float v106; // [esp+44h] [ebp-24h]
  float v107; // [esp+48h] [ebp-20h]
  float v108; // [esp+4Ch] [ebp-1Ch]
  float v109; // [esp+50h] [ebp-18h] BYREF
  float v110; // [esp+54h] [ebp-14h]
  float v111; // [esp+58h] [ebp-10h]
  float v112; // [esp+5Ch] [ebp-Ch] BYREF
  float v113; // [esp+60h] [ebp-8h]
  float v114; // [esp+64h] [ebp-4h]

  v109 = *a3 - *a1;
  v110 = a3[1] - a1[1];
  v111 = a3[2] - a1[2];
  v97 = *a4 - *a1;
  v98 = a4[1] - a1[1];
  v99 = a4[2] - a1[2];
  v100 = *a5 - *a1;
  v101 = a5[1] - a1[1];
  v102 = a5[2] - a1[2];
  v5 = v109;
  v103 = v97 - v109;
  v104 = v98 - v110;
  v105 = v99 - v111;
  v6 = v111;
  v106 = v100 - v97;
  v107 = v101 - v98;
  v108 = v102 - v99;
  v112 = v109 - v100;
  v113 = v110 - v101;
  v114 = v111 - v102;
  v94 = fabs(v103);
  v91 = fabs(v104);
  v88 = fabs(v105);
  v7 = v105;
  v67 = v110 * v105 - v104 * v111;
  v8 = v102;
  v49 = v101 * v105 - v104 * v102;
  v9 = v67;
  v10 = v49;
  if ( v49 > (double)v67 )
  {
    v10 = v67;
    v9 = v49;
  }
  v37 = v10;
  v68 = a2[2] * v91 + v88 * a2[1];
  if ( v68 < (double)v37 )
    return 0;
  v50 = v9;
  if ( -v68 > v50 )
    return 0;
  v69 = v103 * v6 - v7 * v5;
  v11 = v103 * v8 - v7 * v100;
  v12 = v103;
  v51 = v11;
  v13 = v69;
  v14 = v51;
  if ( v51 > (double)v69 )
  {
    v14 = v69;
    v13 = v51;
  }
  v38 = v14;
  v70 = *a2 * v88 + a2[2] * v94;
  if ( v70 >= (double)v38 )
  {
    v52 = v13;
    if ( -v70 <= v52 )
    {
      v83 = v104 * v97 - v12 * v98;
      v53 = v104 * v100 - v12 * v101;
      v15 = v53;
      v16 = v83;
      if ( v83 > (double)v53 )
      {
        v16 = v53;
        v15 = v83;
      }
      v39 = v16;
      v71 = *a2 * v91 + v94 * a2[1];
      if ( v71 >= (double)v39 )
      {
        v54 = v15;
        if ( -v71 <= v54 )
        {
          v17 = v106;
          v95 = fabs(v106);
          v92 = fabs(v107);
          v89 = fabs(v108);
          v18 = v108;
          v72 = v108 * v110 - v107 * v6;
          v55 = v108 * v101 - v107 * v8;
          v19 = v72;
          if ( v55 <= (double)v72 )
          {
            v40 = v108 * v101 - v107 * v8;
          }
          else
          {
            v40 = v108 * v110 - v107 * v6;
            v19 = v55;
          }
          v73 = a2[2] * v92 + v89 * a2[1];
          if ( v73 >= (double)v40 )
          {
            v56 = v19;
            if ( -v73 <= v56 )
            {
              v74 = v17 * v6 - v18 * v5;
              v20 = v8 * v17 - v18 * v100;
              v21 = v106;
              v57 = v20;
              v22 = v74;
              v23 = v57;
              if ( v57 > (double)v74 )
              {
                v23 = v74;
                v22 = v57;
              }
              v41 = v23;
              v75 = *a2 * v89 + a2[2] * v95;
              if ( v75 >= (double)v41 )
              {
                v58 = v22;
                if ( -v75 <= v58 )
                {
                  v76 = v107 * v5 - v21 * v110;
                  v84 = v107 * v97 - v21 * v98;
                  v24 = v76;
                  v25 = v84;
                  if ( v84 > (double)v76 )
                  {
                    v25 = v76;
                    v24 = v84;
                  }
                  v42 = v25;
                  v77 = *a2 * v92 + v95 * a2[1];
                  if ( v77 < (double)v42 )
                    return 0;
                  v59 = v24;
                  if ( -v77 > v59 )
                    return 0;
                  v26 = v112;
                  v96 = fabs(v112);
                  v27 = v113;
                  v93 = fabs(v113);
                  v90 = fabs(v114);
                  v28 = v114;
                  v78 = v110 * v114 - v113 * v6;
                  v85 = v114 * v98 - v113 * v99;
                  v29 = v78;
                  if ( v85 <= (double)v78 )
                  {
                    v43 = v114 * v98 - v113 * v99;
                  }
                  else
                  {
                    v43 = v110 * v114 - v113 * v6;
                    v29 = v85;
                  }
                  v79 = a2[2] * v93 + v90 * a2[1];
                  if ( v79 < (double)v43 )
                    return 0;
                  v60 = v29;
                  if ( -v79 > v60 )
                    return 0;
                  v80 = v26 * v6 - v28 * v5;
                  v30 = v26 * v99 - v28 * v97;
                  v31 = v97;
                  v86 = v30;
                  v32 = v80;
                  if ( v86 <= (double)v80 )
                  {
                    v44 = v86;
                  }
                  else
                  {
                    v44 = v80;
                    v32 = v86;
                  }
                  v81 = *a2 * v90 + a2[2] * v96;
                  if ( v81 < (double)v44 )
                    return 0;
                  v61 = v32;
                  if ( -v81 > v61 )
                    return 0;
                  v87 = v27 * v31 - v26 * v98;
                  v62 = v27 * v100 - v26 * v101;
                  v33 = v62;
                  v34 = v87;
                  if ( v87 > (double)v62 )
                  {
                    v34 = v62;
                    v33 = v87;
                  }
                  v45 = v34;
                  v82 = *a2 * v93 + v96 * a2[1];
                  if ( v82 < (double)v45 )
                    return 0;
                  v63 = v33;
                  if ( -v82 > v63 )
                    return 0;
                  v35 = v100;
                  v64 = v109;
                  v46 = v109;
                  if ( v109 > v31 )
                    v46 = v97;
                  if ( v109 < v31 )
                    v64 = v97;
                  if ( v46 > v35 )
                    v46 = v100;
                  if ( v64 < v35 )
                    v64 = v100;
                  if ( *a2 >= (double)v46 && -*a2 <= v64 )
                  {
                    v65 = v110;
                    v47 = v110;
                    if ( v98 < (double)v110 )
                      v47 = v98;
                    if ( v98 > (double)v110 )
                      v65 = v98;
                    if ( v47 > (double)v101 )
                      v47 = v101;
                    if ( v65 < (double)v101 )
                      v65 = v101;
                    if ( a2[1] >= (double)v47 && -a2[1] <= v65 )
                    {
                      v66 = v111;
                      v48 = v111;
                      if ( v99 < v6 )
                        v48 = v99;
                      if ( v99 > v6 )
                        v66 = v99;
                      if ( v48 > (double)v102 )
                        v48 = v102;
                      if ( v66 < (double)v102 )
                        v66 = v102;
                      if ( a2[2] >= (double)v48 && -a2[2] <= v66 )
                      {
                        v112 = v108 * v104 - v107 * v105;
                        v113 = v105 * v106 - v108 * v103;
                        v114 = v103 * v107 - v106 * v104;
                        return sub_10001010(&v112, a2, &v109);
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    return 0;
  }
  return 0;
}
```

the sub_10001010 see below
```
BOOL __usercall sub_10001010@<eax>(float *a1@<edx>, float *a2@<ecx>, float *a3@<esi>)
{
  double v3; // st6
  double v4; // st6
  double v5; // st6
  double v6; // st6
  double v7; // st7
  double v8; // st7
  double v9; // st7
  double v10; // st6
  double v11; // st5
  float v13; // [esp+4h] [ebp-18h]
  float v14; // [esp+8h] [ebp-14h]
  float v15; // [esp+Ch] [ebp-10h]
  float v16; // [esp+10h] [ebp-Ch]
  float v17; // [esp+14h] [ebp-8h]
  float v18; // [esp+18h] [ebp-4h]

  v3 = *a3;
  if ( *a1 <= 0.0 )
  {
    v13 = *a2 - v3;
    v4 = -*a2 - v3;
  }
  else
  {
    v13 = -*a2 - v3;
    v4 = *a2 - v3;
  }
  v16 = v4;
  v5 = a3[1];
  if ( a1[1] <= 0.0 )
  {
    v14 = a2[1] - v5;
    v6 = -a2[1] - v5;
  }
  else
  {
    v14 = -a2[1] - v5;
    v6 = a2[1] - v5;
  }
  v17 = v6;
  v7 = a3[2];
  if ( a1[2] <= 0.0 )
  {
    v15 = a2[2] - v7;
    v8 = -a2[2] - v7;
  }
  else
  {
    v15 = -a2[2] - v7;
    v8 = a2[2] - v7;
  }
  v18 = v8;
  v9 = a1[1];
  v10 = *a1;
  v11 = a1[2];
  return v13 * v10 + v14 * v9 + v15 * v11 <= 0.0 && v9 * v17 + v10 * v16 + v11 * v18 >= 0.0;
}
```

**Comment by Xian55** [comment]
Im pretty sure `ccode.dll` is an Axis aligned bounding box test function similar to this one.

https://gist.github.com/StagPoint/76ae48f5d7ca2f9820748d08e55c9806
https://github.com/perfume-dev/VoxelEditor/blob/master/src/triboxoverlap.h

**Comment by coolzoom** [comment]
> Im pretty sure `ccode.dll` is an Axis aligned bounding box test function similar to this one.
> 
> https://gist.github.com/StagPoint/76ae48f5d7ca2f9820748d08e55c9806 https://github.com/perfume-dev/VoxelEditor/blob/master/src/triboxoverlap.h

Amazing!! can we just replace the dll with the c# code?

**Comment by Xian55** [comment]
Sure, i would love to get rid of that dll. Just be sure to check to to get the same output. 🙇

**Comment by coolzoom** [comment]
> Sure, i would love to get rid of that dll. Just be sure to check to to get the same output. 🙇

Sweet! i just did a test by simple copy paste, it works! by compare the navigation path with clean code, they looks identical.

https://github.com/coolzoom/WowClassicGrindBot/commit/69224750bed25b4f990be7d653cfe8248bbfa6da

**Comment by Xian55** [comment]
Nice one, at first glance, it seems you can apply [in parameter modifier](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier) for the vector3.

In theory should perform the same or even better since Vector3 [SIMD](https://docs.microsoft.com/en-us/dotnet/standard/simd) accelerated.

Take your time, to read about this, and judge after.

**Comment by coolzoom** [comment]
> Nice one, at first glance, it seems you can apply [in parameter modifier](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier) for the vector3.
> 
> In theory should perform the same or even better since Vector3 [SIMD](https://docs.microsoft.com/en-us/dotnet/standard/simd) accelerated.
> 
> Take your time, to read about this, and judge after.

Thanks! I always love to learn more! will read through it and see what I can get.

**Comment by coolzoom** [comment]
All right, I did some clean up, Replace the old function with the new one. hope i did it correctly xD
Also i tested the StormLib.dll at x64 mode, it appears some bug for the SFileOpenArchive function at x64 mode, 
I have opened an issue to Ladislav-Zazula's StormLib repo, it might be I did it wrongly, but let's see what he responds

**Comment by Xian55** [comment]
> SFileOpenArchive function at x64 mode

Like i mentioned before, ran into `BadImageException` upon calling `SFileOpenArchive` x64 build. So you are not the first. i eagerly await the response.

**Comment by coolzoom** [comment]
Waiting for the response and fix may take a while, 
Also, we need to support both MPQ and the CASC(for retail),
Do you think it is better to just extract the required map data and use a common zip library?

**Comment by Xian55** [comment]
MPQ has an expected end of life time. Working fine as of now.

CASC support would be nice if possible.

Im pretty sure somebody already found a way to create mmap tiles just like TrinityCore did.

One of my fellow already shared with me https://forums.getgud.cc/ site, where you can download nav mesh files. I was yet to figure out what extractor process they used. It seemed somewhat similar to TrinityCore, but after a short peek, its seems to be a different encoding type, as the `MMAP_MAGIC ` is different then what Trinity Core uses.

https://github.com/TrinityCore/TrinityCore/blob/master/src/common/Collision/Maps/MMapDefines.h

**Comment by coolzoom** [comment]
> MPQ has an expected end of life time. Working fine as of now.
> 
> CASC support would be nice if possible.
> 
> Im pretty sure somebody already found a way to create mmap tiles just like TrinityCore did.
> 
> One of my fellow already shared with me https://forums.getgud.cc/ site, where you can download nav mesh files. I was yet to figure out what extractor process they used. It seemed somewhat similar to TrinityCore, but after a short peek, its seems to be a different encoding type, as the `MMAP_MAGIC ` is different then what Trinity Core uses.
> 
> https://github.com/TrinityCore/TrinityCore/blob/master/src/common/Collision/Maps/MMapDefines.h

Do you play wow emulator? 
they probably use the extractor and recast from cmangos https://github.com/cmangos/mangos-tbc, the cmangos recast pathfinding is better than trinity core. it has the recast demo that we could use to simulate the navigation by mouse click.
https://github.com/cmangos/mangos-tbc/blob/master/dep/recastnavigation/RecastDemo/screenshot.png

AzerothCore extractor is pretty much similar to TrinityCore as it doesn't have good path findings.

so if we are going to use the recast navigation, will have to get the cordinate from the memory, 
the Addon does not return the xyzo and uimapid inside dungeons, also the wordmaparea.json lacks a lot of data so we could not use it as well.

Getting the offset from wow.exe is fast using the cheat engine for XYZO and MapID, we don't need other stuff for now.
from the link you supplied, they are using Lua unlocker which requires a lot of effort and is very risky because of memory changing. 
though it brings a lot of possibility after unlocking the Lua but may not an easy/preferred way.

so if we still use the ppatcher method, we could just extract the data from the client.
If we are going to use mmap, appears hooking memory to get the xyzo and map id is necessary.

**Comment by Xian55** [comment]
> Do you play wow emulator?

Not sure what you asking about this one. Private servers using old client. DataToColor addon probably not compatible with private servers.

Yes, i've used the recastnavigation demo before, to test the RemoteV3 mmap settings. 

Would be interesting to look at cmangos mmaps beside trinity one. However it seems they don't have the capacity for retail(shadowlands) current version.

> wordmaparea.json lacks a lot of data so we could not use it as well.

What kind of data you are missing? Instance info left out intentionally, as currently there are no movement capabilities and with the current skillset(very limited) it has a really small chance to make a working profile inside the dungeon. The combat works best with one target only as of now.

Just to give one more reasoning why memory scanning is far away from the project scope is that, the other components in the project have to mature in order to gain the benefit of reading xyzo.

Imho we are getting a bit side track here, i just gave the link for possible working navmesh, lua unlocker and memory reading is out of context to the conversation.

**Comment by coolzoom** [comment]
>Not sure what you asking about this one. Private servers using old client. DataToColor addon probably not compatible with private servers.

No worries, i just mention that if you wish to generate the mmap extractor, can clone the code from TrinityCore or cmangos, open cmake, during cmake there is option to select "Generate Tools" which will generate the extractor project including maps/mmps. after compile will get the mmap generator binary.

> Would be interesting to look at cmangos mmaps beside trinity one. However it seems they don't have the capacity for retail(shadowlands) current version.

Yes for retail, the trinitycore extractor and mmap generator was the only one for now. but it is possible to pick the recast and mmap code from cmangos and make it to work with current trinity core so can get better path results. but i havent really tested

>Imho we are getting a bit side track here, i just gave the link for possible working navmesh, lua unlocker and memory reading is out of context to the conversation.

Yes, understand, sorry for the out-of-topic.

I will keep playing around with it.

**Comment by coolzoom** [comment]
there is casc library, in both c++ and c# 
https://github.com/ladislav-zezula/CascLib
https://github.com/WoW-Tools/CascLib
, but moving forward there is no benefit we spend time to support the casc file system, even we could read the casc files, we will have to write a lot of functions to read the different version game files (adt,m2,wmo etc), and the casc file system is also changing.

the PPather read in the ADT, WMO, M2 files, etc, these files are changing from version to version, we could not handle all the format, even we can, if there is new version came out, we will have to change the code again to adapt the new file format.
the wowdev.wiki has all those defined in details, eg:
https://wowdev.wiki/ADT/v18

so, based on my check:
for game version equal or less than WLK(including wlk classic), ppather still the best choice.
for game version larger than WLK, including retail, will have to use the recast version(mmaps). CASC will not bring help to the project.

**Comment by Xian55** [comment]
Thanks for the detailed findings.

**Pull request closed without merging**
