### PR TITLE
Core: `BeforeCastDismount` option added for KeyAction

### LINKED ISSUE #413: Dismounts to cast Crusader Aura
### Description

After mounting I want to cast Crusader Aura, Crusader can be cast while on a mount

### Addon Version

1.7.17

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

When the character mounts it will then dismount to cast Crusader Aura. 
{
        "Name": "Crusader Aura",
        "Key": "N9",
        "Requirements": [
		  "Mounted",
          "!Form:Paladin_Crusader_Aura"
        ],
		"AfterCastWaitBuff": true
      },

### Last Good Version

n/a

### Screenshots

_No response_

### Logs

[out20220830.log](https://github.com/Xian55/WowClassicGrindBot/files/9456902/out20220830.log)

### PR DESCRIPTION
**Pull request by AsterNighT**
Allow adhoc goals to be dealt mounted. Could be somehow extended to other goals.
Not really tested yet. I don't really have a paladin character, help is apprieciated.
Should fix #413

Signed-off-by: AsterNighT <asternight@outlook.com>

### CODE REVIEW

**Comment by AsterNighT** [comment]
Freak I got banned again. Really need someone to test this.

**Comment by Xian55** [comment]
Good day, sorry to hear that.

I suggest to avoid using any kind of automation software on your account, if it was the same as last time. Your account most likely flagged.

I recommend, using a disposable account for the purpose. 🙇

**Comment by Xian55** [comment]
The idea is really cool. i like it.

However, i would like to fit the keyword to the already existing ones.

`AllowMounted` seems to vague for me. Rather apply to the same naming scheme `BeforeCastDismount` which is an already existing feature and this PR allows to disable it.

**Comment by Xian55** [comment]
Thank you for the contribution!

**Pull request merged**
