### PR TITLE
Compile stormlib with VS2017_xp

### PR DESCRIPTION
**Pull request by coolzoom**
Might fix this issue, 
https://github.com/Xian55/WowClassicGrindBot/pull/368#issuecomment-1203973954

the original was compiled using the vs2010 compiler for better compatibility consideration, so it might be a lack of code optimization during compilation compared with the modern compiler(eg:vs2019 v142).
Now change to use the latest compiler and SDK. the x64 version still uses higher mem than x86 but I think it is now a reasonable value.

tested using this path:
* start PathingAPI and scroll down to click on [Dun morogh Coldrige pass](http://localhost:5001/api/PPather/MapRoute?uimap1=1426&x1=33.76&y1=71.91&uimap2=1426&x2=39.0&y2=61.13)
* notes that the above path has no valid path found.

Compare:

IDEVS2022 compiler vs2010, no windows SDK
image
IDE VS2022, Compiler vs2019(v142) Windows SDK 10.0.19041.0
image

@Xian55  please have a look see how it performs at your pc

### CODE REVIEW

**Comment by Xian55** [comment]
Hi, be sure to delete the `\Json\PathInfo\Azeroth` folder before each attempt, in order to avoid reading from cache.

**Comment by coolzoom** [comment]
> Hi, be sure to delete the `\Json\PathInfo\Azeroth` folder before each attempt, in order to avoid reading from cache.

Yup, thats what i did. confirmed

**Comment by Xian55** [comment]
> notes that the above path has no valid path found.

Yes with the default `A* avoid models` search type it fails to find the path. I usually test with this, its short, and consistently fails.

release build, ye well x86 still okay at my side. x64 dropped about 330mb, in this scenario from 1.1gb to 830mb.

**Comment by Xian55** [comment]
I was doing the tests with debugger attached. 

Without debgger attached it seems the memory used even lower. pretty similar what you shared with `IDE VS2022, Compiler vs2019(v142) Windows SDK 10.0.19041.0`

**Comment by Xian55** [comment]
There's like one drawback with this setup, it requires windows `10.0.19041.0` version to be installed isn't it?

As minimum OS requirement.

**Comment by Xian55** [comment]
After some digging, it only requires have the same VC++ runtime to be installed.

It remains compatible with old operation systems as long as not using some newer OS based feature.

My concern is that, in the past, the solution was working from windows 7.

**Comment by coolzoom** [comment]
> After some digging, it only requires have the same VC++ runtime to be installed.
> 
> It remains compatible with old operation systems as long as not using some newer OS based feature.
> 
> My concern is that, in the past, the solution was working from windows 7.

the stormlib has changed some, in older comipler it indeed has better compactablilty, but back in that time not too many people were really testing the mem consumption at x64 mode i think. 
let me see if i can compile it with a lower visuual studio.
Update: it appears we could install the xp support for visual studio 2017 so it compactable back to windows xp, going to do some tests on this
https://stackoverflow.com/questions/49516896/how-to-install-build-tools-for-v141-xp-for-vc-2017

**Comment by coolzoom** [comment]
at x64 mode, Better than the vs2010 compiler but worse than the vs2019 compiler,
at x86 mode there isn't really much has changed, but it appears the modern compiler and windows SDK has better performance at x64 mode, appears we will have to make some compromise. 
@Xian55 can you also have a try?

image

**Comment by Xian55** [comment]
Really interesting...

**Comment by Xian55** [comment]
Might be related, https://github.com/ladislav-zezula/StormLib/issues/141

This seems really sketchy
https://github.com/ladislav-zezula/StormLib/commit/f35d106059accbddaa602b6525f9542746b2c2b7#diff-2c6a2259a9d870c70382f22e84b3ca55a49fac934a431530af59ab4f148df1db

**Comment by coolzoom** [comment]
> Might be related, [ladislav-zezula/StormLib#141](https://github.com/ladislav-zezula/StormLib/issues/141)
> 
> This seems really sketchy [ladislav-zezula/StormLib@f35d106#diff-2c6a2259a9d870c70382f22e84b3ca55a49fac934a431530af59ab4f148df1db](https://github.com/ladislav-zezula/StormLib/commit/f35d106059accbddaa602b6525f9542746b2c2b7#diff-2c6a2259a9d870c70382f22e84b3ca55a49fac934a431530af59ab4f148df1db)

hmm he mentioned he has fixed that.

**Comment by coolzoom** [comment]
I just did few more tests, by cleaning everything and restart the api, it now keeps at below 420MB, not sure why the first time it consumes me 500MB though.
is this same for you? if so i think it might be acceptable.
image

**Comment by Xian55** [comment]
if its x64, seems way better than 800mb. yes thats acceptable

**Comment by coolzoom** [comment]
> if its x64, seems way better than 800mb. yes thats acceptable

yes above image is for x64, you can see it doesnt have (32) beside the application name
below is what x86 consumes
image

**Comment by Xian55** [comment]
im convinced, let me know when i can merge.

**Comment by coolzoom** [comment]
let me squash the commits so it is cleaner

**Comment by coolzoom** [comment]
should be ok now, please review and merge

**Comment by coolzoom** [comment]
just a side question, How can I run the PathAPI in a VPS with IP address? Tried to change the IP binding but it wont startup
using default 127.0.0.1:5001 i couldn't access from my pc

**Comment by Xian55** [comment]
As of now PathingAPI uses
https://github.com/Xian55/WowClassicGrindBot/blob/43e747f3250e798f15a8697616297f192f7ec3c6/PathingAPI/Program.cs#L10

be sure to firewall doesn't block.

For blazorServer, be sure to edit at the right location i mean `appsettings.json`. edit accordingly `RemoteV1` is PPAther = PathingAPI
https://github.com/Xian55/WowClassicGrindBot/blob/dev/BlazorServer/appsettings.json

HeadlessServer - `-mode RemoteV1` `hostv1` and `portv1`
https://github.com/Xian55/WowClassicGrindBot/blob/dev/HeadlessServer/RunOptions.cs

**Comment by Xian55** [comment]
Consider join to https://discord.gg/wcANhzd

**Comment by coolzoom** [comment]
> Consider joining https://discord.gg/yyYB7GJ

Joined but is there anything wrong with the server?
I got "message failed to load" no matter how

image

**Comment by coolzoom** [comment]
> > Consider joining https://discord.gg/yyYB7GJ
> 
> Joined but is there anything wrong with the server? I got "message failed to load" no matter how
> 
> image

Never mind, it appears i found a discord bug. when there is no message, after you first join the server, it always shows Messages Failed to load, until you get the first event notice from that server.

**Pull request merged**
